/* * JAVA COMMUNITY PROCESS * * J S R  9 4 * * Test Compatibility Kit * */package org.jcp.jsr94.tck;import org.junit.jupiter.api.Test;import javax.rules.RuleExecutionException;/** * Test the javax.rules.RuleExecutionException class. * <p> * <b>Performs the following tests:</b><br> * <ul> * <li>Basic API tests. {@link #testRuleExecutionException} * <ul> * <li>Instance Creation * <li>Class Hierarchy * <li>Exception Wrapping * </ul> * </ul> * * @version 1.0 * @see javax.rules.RuleExecutionException * @since JSR-94 1.0 */public class RuleExecutionExceptionTest {    /**     * Test the compliance for javax.rules.RuleExecutionException.     *     * <p>     * <b>Description:</b><br>     * Create two instances of the RuleExecutionException class. The first     * instance will be constructed with an additional message. The     * second instance will have its own message as well as wrap the     * first instance. The class hierarchy will be tested. The second     * exception will be thrown. The exception will be caught and the     * test will verify whether the exception can successfully be     * unwrapped.     * The following tests will be performed.     * <ul>     * <li>Instance Creation     * <ul>     * <li>Fail: If RuleExecutionException cannot be created by any of     * the JSR specified constructor.     * <li>Succeed: If the exception can successfully be created.     * </ul>     * <li>Class Hierarchy     * <ul>     * <li>Fail: If superclass is not a RuleException     * <li>Succeed: If the exception is instance of RuleException.     * </ul>     * <li>Exception Wrapping     * <ul>     * <li>Fail: If any other than the the original     * RuleExecutionException is unwrapped.     * <li>Succeed: If exception can successfully be unwrapped.     * </ul>     * </ul>     */    @Test    void testRuleExecutionException() {        RuleExecutionException re1 = null;        RuleExecutionException re2 = null;        try {            re1 = new RuleExecutionException("jsr94-test-rule-execution-exception");            re2 = new RuleExecutionException("jsr94-test-embedded-rule-execution-exception", re1);            // Throw it.            throw re2;        } catch (RuleExecutionException ex) {            // Catch it.            Throwable t = ex.getCause();            assert t.equals(re1);            // The thrown exception should be re2.            assert ex.equals(re2);        } catch (Exception e) {            throw new IllegalStateException();        }    }}